core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.order, name='order'),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
]

shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

import core
from core import views

from order import views as OrderViews
from user import views as UserViews
from favorites import views as FavoriteViews


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('home/', include('core.urls')),

    path('product/', include('product.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls')),
    path('favorites/', include('favorites.urls')),

    path('about/', views.aboutus, name='aboutus'),
    path('contact/', views.contactus, name='contactus'),
    path('newlogin/', views.newlogin, name='newlogin'),
    path('collection/', views.collection, name='collection'),

    path('search/', views.search, name='search'),
    path('search_auto/', views.search_auto, name='search_auto'),

    path('category/<int:id>/<slug:slug>', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),

    path('shopcart/', OrderViews.shopcart, name='shopcart'),
    path('favoritecart/', FavoriteViews.favoritecart, name='favoritecart'),
    path('orders/', UserViews.user_orders, name='user_orders'),

    path('login/', UserViews.login_form, name='login_form'),
    path('logout/', UserViews.logout_func, name='logout_func'),
    path('signup/', UserViews.signup_form, name='signup_form'),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/',
        auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
     name="password_reset_confirm"),

    path('reset_password_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),
        name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm

from product.models import Product, Variants

class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']



class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status = models.CharField(max_length=10,choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city', 'country']



class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotAllowed
from django.utils.crypto import get_random_string

from order.models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from product.models import Category, Product
from user.models import UserProfile



@login_required(login_url='/login')  # Check login
def addtoshopcart(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # Access User Session information
    checkproduct = ShopCart.objects.filter(product_id=id)

    if checkproduct:
        control = 1  # The product is in the cart
    else:
        control = 0  # The product is not in the cart"""

    if request.method == 'POST':  # if there is a post
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control == 1:  # Update  shopcart
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else:
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, "Product added to Shopcart ")
        return HttpResponseRedirect(url)

    else:  # if there is no post
        if control == 1:  # Update  shopcart
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()  #
        else:  # Inser to Shopcart
            data = ShopCart()  # model ile bağlantı kur
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()  #
        messages.success(request, "Product added to Shopcart")
        return HttpResponseRedirect(url)




def shopcart(request):
    category = Category.objects.all()
    current_user = request.user  # Access User Session information
    shopcart = ShopCart.objects.filter(user_id=current_user.id)

    total = 0
    for i in shopcart:
        total += i.product.price * i.quantity

    context = {
        'category': category,
        'shopcart': shopcart,
        'total': total,
    }
    return render(request, 'shopcart_products.html', context)



@login_required(login_url='/login')  # Check login
def deletefromcart(request, id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Your item deleted from Shopcart.")
    return HttpResponseRedirect("/shopcart/")



def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user  # Access User Session information
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    profile = UserProfile.objects.get(user_id=current_user.id)
    total = 0
    for i in shopcart:
        total += i.product.price * i.quantity

    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        # return HttpResponse(request.POST.items())
        if form.is_valid():
            # Send Credit card to bank,  If the bank responds ok, continue, if not, show the error
            # ..............

            data = Order()
            data.first_name = form.cleaned_data['first_name']  # get product quantity from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()  # random cod
            data.code = ordercode
            data.save()  #

            shopcart = ShopCart.objects.filter(user_id=current_user.id)
            for i in shopcart:
                detail = OrderProduct()
                detail.order_id = data.id  # Order Id
                detail.product_id = i.product_id
                detail.user_id = current_user.id
                detail.quantity = i.quantity
                detail.price = i.product.price
                detail.amount = i.amount
                detail.save()

                product = Product.objects.get(id=i.product_id)
                product.amount -= i.quantity
                product.save()

            ShopCart.objects.filter(user_id=current_user.id).delete()  # Clear & Delete shopcart
            request.session['cart_items'] = 0
            messages.success(request, "Your Order has been completed. Thank you ")
            return render(request, 'Order_Completed.html', {'ordercode': ordercode, 'category': category})

        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm()
    context = {
        'category': category,
        'shopcart': shopcart,
        'total': total,
        'profile': profile,
        'form': form,
    }
    return render(request, 'Order_Form.html', context)


def order(request):
    return HttpResponse("order")

order/templates/Order_Completed.html
{% extends 'home.html' %}

{% block title %} Order Completed {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Completed</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
    <!-- container -->
    <div class="container">
    <div class="row">

        <div class="col-md-12">
            <div class="order-summary clearfix">
                <div class="section-title">
                    <h3 class="title">Order Completed</h3>
                </div>
                <hr>
                <h2>Dear {{ user.first_name }} {{ user.last_name }}</h2>
                <hr>
                <h3>Your order is completed</h3>
                <h3>Order Code: {{ ordercode }}</h3>
                <h3>Thank you</h3>
            </div>

        </div>


    </div>

    <!-- /section -->

{% endblock %}

order/templates/Order_Form.html
{% extends 'home.html' %}

{% block title %} Order Form {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Form</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
    <!-- container -->
    <div class="container">
    <!-- row -->

    <div class="row">
    <Form action="" method="post">
                    {% csrf_token %}
                    <div class="col-md-pull-6">
                        <div class="billing-details">

                            <div class="section-title">
                                <h4 class="title">Shipping Details</h4>
                            </div>
                            <p><label for="id_first_name">First name:</label>
                                <input type="text" name="first_name"  value="{{ user.first_name }}" class="input" maxlength="10" required id="id_first_name"></p>
                            <p><label for="id_last_name">Last name:</label>
                                <input type="text" name="last_name"  value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name"></p>
                            <p><label for="id_address">Address:</label>
                                <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address"></p>
                            <p><label for="id_phone">Phone:</label>
                                <input type="text" name="phone"  value="{{ profile.phone }}"  class="input" maxlength="20" id="id_phone"></p>
                            <p><label for="id_city">City:</label>
                                <select name="city" class="input" id="id_city">
                                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                    <option value="Bishkek">Bishkek</option>
                                    <option value="Talas">Talas</option>
                                </select></p>
                            <p><label for="id_first_name">Country :</label>
                                <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}"></p>
                            <div class="pull-right">
                                <button  type="submit" class="primary-btn">Complete Order</button>
                            </div>
                        </div>
                    </div>
                </Form>
        <div class="col-md-12">
            <div class="order-summary clearfix">
                <div class="section-title">
                    <h3 class="title">Shopcart Product List</h3>
                </div>
                <table class="shopping-cart-table table">
                    <thead>
                    <tr>
                        <th>Product</th>
                        <th></th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Quantity</th>
                        <th class="text-right"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in shopcart %}
                        <tr>
                            <td class="thumb"><img src="{{ i.product.image.url }}" alt="" style="height: 45px"></td>
                            <td class="details"><a
                                    href="/product/>{{ i.product.id }}/{{ i.product.slug }}">{{ i.product }}</a></td>
                            <td class="price text-center"><strong>{{ i.product.price }} сом</strong><br></td>
                            <td class="qty text-center"><strong>{{ i.quantity }}</strong></td>
                            <td class="total text-center"><strong class="primary-color">{{ i.amount }} сом</strong></td>
                            <td class="text-right"><a href="/order/deletefromcart/{{ i.id }}"
                                                      onclick="return confirm('You want to delete it?')"
                                                      class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>SHIPPING</th>
                        <td colspan="2">Free Shipping</td>
                    </tr>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>TOTAL</th>
                        <th colspan="2" class="total">{{ total }} сом</th>
                    </tr>
                    </tfoot>
                </table>
                </table>
            </div>

        </div>


    </div>

    <!-- /section -->

{% endblock %}

order/templates/favorites_products.html
{% extends 'home.html' %}

{% block title %} Favorites Products {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Favorites Products</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
    <!-- container -->
    <div class="container">
    <div class="row">

        <div class="col-md-12">
            <div class="order-summary clearfix">
                <div class="section-title">
                    <h3 class="title">Favorites Products List</h3>
                </div>
                <table class="shopping-cart-table table">
                    <thead>
                    <tr>
                        <th>Product</th>
                        <th></th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Image</th>
                        <th class="text-right"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in favorite_products %}
                        <tr>
                            <td class="thumb"><img src="{{ i.product.image.url }}" alt="" style="height: 45px"></td>
                            <td class="details"><a
                                    href="/product/>{{ i.product.id }}/{{ i.product.slug }}">{{ i.product }}</a></td>
                            <td class="price text-center"><strong>{{ i.product.price }} сом</strong><br></td>
                            <td class="text-right"><a href="/order/deletefromcart/{{ i.id }}"
                                                      onclick="return confirm('You want to delete it?')"
                                                      class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>


    </div>

    <!-- /section -->

{% endblock %}

order/templates/shopcart_products.html
{% extends 'home.html' %}

{% block title %} Shop Cart {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Shop Cart</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
    <!-- container -->
    <div class="container">
    <div class="row">

        <div class="col-md-12">
            <div class="order-summary clearfix">
                <div class="section-title">
                    <h3 class="title">Shopcart Product List</h3>
                </div>
                <table class="shopping-cart-table table">
                    <thead>
                    <tr>
                        <th>Product</th>
                        <th></th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Quantity</th>
                        <th class="text-right"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in shopcart %}
                        <tr>
                            <td class="thumb"><img src="{{ i.product.image.url }}" alt="" style="height: 45px"></td>
                            <td class="details"><a
                                    href="/product/>{{ i.product.id }}/{{ i.product.slug }}">{{ i.product }}</a></td>
                            <td class="price text-center"><strong>{{ i.product.price }} сом</strong><br></td>
                            <td class="qty text-center"><strong>{{ i.quantity }}</strong></td>
                            <td class="total text-center"><strong class="primary-color">{{ i.amount }} сом</strong></td>
                            <td class="text-right"><a href="/order/deletefromcart/{{ i.id }}"
                                                      onclick="return confirm('You want to delete it?')"
                                                      class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>SHIPPING</th>
                        <td colspan="2">Free Shipping</td>
                    </tr>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>TOTAL</th>
                        <th colspan="2" class="total">{{ total }} сом</th>
                    </tr>
                    </tfoot>
                </table>
                <div class="pull-right">
                    <a href="/order/orderproduct" class="primary-btn">Place Order</a>
                </div>
                </table>
            </div>

        </div>


    </div>

    <!-- /section -->

{% endblock %}